language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sb/react-test npm test

after_success:
  - docker build -t sb/multi-client ./client
  - docker build -t sb/multi-nginx ./nginx
  - docker build -t sb/multi-server ./server
  - docker build -t sb/multi-worker ./worker
